### ISSUE TITLE
Is there a way to extract the spatial location of individuals that have been simulated in run.popgensim()?

### ISSUE THREAD

**Issue by michaelschwob** [green-striped-gecko/PopGenReport#9]
I have locations of the initial populations for the simulation. However, I'm wondering if there's a way to have the simulation report locations of the simulated individuals. I'd assume that this is possible because we can pass a cost matrix to the function. Perhaps I'm overlooking something simple.

**Comment by michaelschwob** [comment]
At the moment, it seems that the location for simulated individuals is the same location as the population initially was. Is there a way to have populations migrate and branch off?

**Comment by green-striped-gecko** [comment]
Hi.

Yes it is not really individual based in terms of location (the individuals have the coordinates of the population).

In terms of branching off there is no mechanism either, but you could simply try to build it per hand and use the genind object that is returned at the end of the simulation and split of the population by hand and restart the population(s) again.

Not 100% sure if that makes sense for what you want to do, but should be fairly straight forward.


[maybe you could even set the migration matrix in such a way that migration is zero between this the branching populations and the others and restart with the new migration matrix]


Cheers,Bernd
Currently there is no mechanism build in to

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by michaelschwob** [comment]
Thank you for the response and clarification. Love the package!
